CREATE DATABASE IF NOT EXISTS atm_demo CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE atm_demo;
CREATE TABLE IF NOT EXISTS accounts (
  account_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  customer_name VARCHAR(100) NOT NULL,
  balance BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS cards (
  card_no VARCHAR(32) PRIMARY KEY,
  account_id BIGINT NOT NULL,
  pin_hash CHAR(64) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (account_id) REFERENCES accounts(account_id)
) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS transactions (
  tx_id BIGINT PRIMARY KEY AUTO_INCREMENT,
  account_id BIGINT NOT NULL,
  card_no VARCHAR(32) NOT NULL,
  atm_id BIGINT NOT NULL,
  tx_type ENUM('WITHDRAW','DEPOSIT','TRANSFER','BALANCE') NOT NULL,
  amount BIGINT NOT NULL,
  balance_after BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_account_time (account_id, created_at),
  FOREIGN KEY (account_id) REFERENCES accounts(account_id)
) ENGINE=InnoDB;